services:
  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./open-webui-local:/app/backend/data
      - ./docs:/data/docs
    environment:
      - WEBUI_AUTH=false
      - AUTOMATIC1111_BASE_URL=http://automatic1111:7860
      - ENABLE_IMAGE_GENERATION=True


  ollama:
    image: ollama/ollama:latest  
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-local:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]


  automatic1111:
    build: ./build/automatic1111
    container_name: automatic1111
    restart: always
    ports:
      - "7860:7860"
    volumes:
      - ./stable-diffusion-webui/models:/stable-diffusion-webui/models
      - ./stable-diffusion-webui/repositories:/stable-diffusion-webui/repositories
      - ./stable-diffusion-webui/venv:/stable-diffusion-webui/venv

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    environment:
      - CUDA_VISIBLE_DEVICES=0



